### ISSUE TITLE
Intersections Problem

### ISSUE THREAD

**Issue by zivandar** [FritzsHero/RoadArchitect#1]
When creating an intersection, mesh networks are broken. When I combine the starting and ending points of the path, the line of the objects is broken. I am currently using the project.If you fix it, I'd appreciate it.

**Comment by embeddedt** [comment]
@FritzsHero is watching my repository so I think he is notified of the issue you opened there. Please avoid opening duplicate issues.

**Comment by FritzsHero** [comment]
#embeddedt/RoadArchitect/issues/7
