### ISSUE TITLE
Lock rotation

### ISSUE THREAD

**Issue by RedAlert244** [FritzsHero/RoadArchitect#10]
It would be useful if you add the option that lock rotation of the object in each axis in arbitrary angle. This can solve the problem when edge objects(eg bridge pillars)have terrible position when road generated on a slope
How it will looks in the editor inspector is shown in picture
![ааа](https://user-images.githubusercontent.com/71585917/97761505-ac1a2080-1b27-11eb-88b5-e9ff00e87c06.png)

**Comment by FritzsHero** [comment]
Included in 2.1.0
