### ISSUE TITLE
Strange Traffic Light Positioning

### ISSUE THREAD

**Issue by repa1030** [FritzsHero/RoadArchitect#14]
First of all: Thank you for this amazing project and for maintaining it.

**Describe the bug**
If I build a intersection (just like it is described in the docs) the position of the traffic lights is very bad (see picture). But only for the lights.

**To Reproduce**
1. Create New Project
2. Import RoadArchitect from Rewritten API Branch
3. Insert two Roads
4. Create a simple intersection
5. Set stop type to traffic lights

**Expected behavior**
A intersection with nice positioned traffic lights just like in the videos and docs

**Screenshots**
![grafik](https://user-images.githubusercontent.com/54360863/109521929-1a5af980-7aae-11eb-9ccd-970bf8658c50.png)

**Unity version**
2019.4.14

**Comment by embeddedt** [comment]
@FritzsHero I have a quick-and-dirty patch for this on my branch; feel free to copy it if you wish: https://github.com/embeddedt/RoadArchitect/commit/18bcc7ad682421be54f0eb8e71d8eb1ffa196370

**Comment by FritzsHero** [comment]
Thanks for reporting this.
I'll take a closer look at this. Maybe we'll just use embeddedt fix for 2.0 .
Maybe there is time for a complete traffic light rework in a 2.x release, but I haven't decided about this yet.

**Comment by FritzsHero** [comment]
Fixed in version 2.0.0
