### ISSUE TITLE
Unexpected large terrain deformation when first node of road placed

### ISSUE THREAD

**Issue by marcospgp** [FritzsHero/RoadArchitect#21]
**Describe the bug**

Whenever I place the first node of my road, the terrain gets a huge deformation:

![image](https://user-images.githubusercontent.com/3464445/116582697-89699880-a90d-11eb-97e1-9e54f7b670fb.png)

I have tried moving the terrain around, the road objects around, but nothing changes.

**To Reproduce**
Create a large terrain, place first node, terrain gets deformed.

**Expected behavior**
No deformation unless related to road placement.

**Unity version**

2020.3.5f1

Road architect latest version at time of writing, v1.9_FH

Thanks!

**Comment by RedAlert244** [comment]
Addition. This bug related to the terrain history(TH). It happens when you delete one road system and create another one with the same name on same terrain but with changed heightmap resolution.  As result it reads previous road TH that screw up new terrain. To avoid it you should to delete old terrain history that located in /(project_folder)/TH/...gsd

**Comment by FritzsHero** [comment]
Thanks for reporting this and also for providing these additional details.
After I experimented a bit with changing terrain heightmap resolutions, there were issues with roads updates.
And I also experienced smaller deformations on the terrain, when creating a new road and placing 2 nodes on an changed terrain.
Is the following the correct reproduction?:

1. Create Terrain and RoadSystem
2. Place 2 nodes on Road1
3. Delete the RoadSystem
4. Change heightmap resolution of terrain to higher resolution
5. Create a new RoadSystem with the same name as the prior one
6. Place 2 nodes on Road1


Best Regards

Fritzs

**Comment by RedAlert244** [comment]
Yes, it's correct

**Comment by marcospgp** [comment]
> Addition. This bug related to the terrain history(TH). It happens when you delete one road system and create another one with the same name on same terrain but with changed heightmap resolution. As result it reads previous road TH that screw up new terrain. To avoid it you should to delete old terrain history that located in /(project_folder)/TH/...gsd

Thank you! For me the folder was in `<project folder>/GSD/TH`.

**Comment by FritzsHero** [comment]
Fixed in version 2.0.0
