### ISSUE TITLE
Version 2.0.0 does not work with Unity prior to 2019.2

### ISSUE THREAD

**Issue by AstroLeap** [FritzsHero/RoadArchitect#23]
I tried re-importing and everything I could but when I create a new Road Architect system and click on the road, I cannot hold down shift and click to create nodes

**Comment by FritzsHero** [comment]
Can you give me more details please?
Unity version;
RoadArchitect version;
Operating system and version;

**Comment by RedAlert244** [comment]
Same in 2018.2.x. It seems that unity 2018.2.x. will no longer be supported?

**Comment by FritzsHero** [comment]
I tried it on 5.6 and all LTS versions before release 2.0.0 and it worked. I will check if there are any issues in Unity 2018.2. But I highly recommend to use one of the LTS version, when trying to create a game or program.

**Comment by FritzsHero** [comment]
I clearly missed that TryGetComponent is a relatively new method. It should now work when you use version 2.0.2 .
