### ISSUE TITLE
Update all roads take infinite time!

### ISSUE THREAD

**Issue by parvanehAghajani** [FritzsHero/RoadArchitect#27]
Hello, 
Thank you for maintaining this interesting project!
I am trying to create roads and intersections in the script.
Based on the RoadAutomation descriptions, I set "isAllowingRoadUpdates" to false, after calling "CreateRoadProgrammatically", and "CreateIntersectionsProgrammaticallyForRoad", I set "isAllowingRoadUpdates" to true and call the "UpdateAllRoads()".
But the "UpdateAllRoads()" function takes forever!!
How can I solve this issues?

Thank you

**Comment by FritzsHero** [comment]
Hi,

I think you use this in play mode or ingame? The creation of roads was limited to the edit mode in previous versions. Currently there is no such limitation, but I did not test anything in this direction.
It looks like there are currently issues in the edit mode.
Probably I can fix this shortly. Stay tuned!


Best Regards

Fritzs

**Comment by parvanehAghajani** [comment]
Hello @FritzsHero 

I am creating the roads in the play mode. 

Thank you,
Parvaneh

**Comment by FritzsHero** [comment]
This works since a few versions. Closing this issue.
