### ISSUE TITLE
imported a package and when tried to add extrude objects it says "could not find path to extrude objects". any solution?

### ISSUE THREAD

**Issue by aka179** [FritzsHero/RoadArchitect#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Unity version**

i.e. 2018.2.0f1

**Additional context**

**Comment by aka179** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/90317544/132490199-208a8b0f-311c-433d-ad84-e86863234f62.png)
 screenshot is attached of the error

**Comment by FritzsHero** [comment]
Maybe import did not write all files?
Did you use the package or the files from git.
You could try to overwrite the RoadArchitect files in your project with the files from a git clone or just reimport. This may fix it.

**Comment by FritzsHero** [comment]
No response. Closing this ticket.
