### ISSUE TITLE
extruded road objects created with the same name overwrite each other if "save mesh assets" check is on

### ISSUE THREAD

**Issue by RedAlert244** [FritzsHero/RoadArchitect#29]
it easy to workaround but still annoying when you need rename hundreds of objects

create road with few nodes
turn on "save mesh assets" check
select first node and add custom extrusion object(bridgebase mesh for example)
select second node and add custom extrusion object with same name and mesh
extruded mesh from first node will dissapear (missing mesh)

you should add script that will detect extrusion objects with the same name and give them unique e.g extrudedobject, extudedobject(1), extrudedobject(2)...(3)...(4)

unity 2018.2.0f2

**Comment by FritzsHero** [comment]
Main problem will be how and when we delete these meshes.
I did quickly implement this just for extruded objects, but it will keep saving new assets when updating the same road.
Leaving the old unused assets still in place.

Example with 2 KRails:
1. Road is updated
2. SceneName + RoadName + KRail as a name is created
3. SceneName + RoadName + KRail + 1 is created
4. Road is updated again
5. SceneName + RoadName + KRail + 2 is created
6. SceneName + RoadName + KRail + 3 is created

So the Generated folder will fill up with meshes that never get deleted.
Should we just give a note about this?
Should we delete the meshes upon updating this particular road in this scene?
Is there better solution to this problem?

**Comment by FritzsHero** [comment]
And out of curiosity why do you use this option to save the meshes?

**Comment by RedAlert244** [comment]
we can try to run "check name" script when "add new object" button is clicked

**Comment by RedAlert244** [comment]
i use unity engine and road architect to create custom maps for the game on unity. After all to load my map into the game whole scene must be exported as asset bundle. Idk why but meshes that stored into the scene will not visible in game.

**Comment by FritzsHero** [comment]
That actually sounds like the best solution. I look into it as soon as I find time for it.
Thanks for that info. It is always nice to see someone who is using this asset.

**Comment by FritzsHero** [comment]
This is now included in the 2.4.0 version.
Feel free to comment if it is good enough.
