### ISSUE TITLE
RoadUtility Namespace

### ISSUE THREAD

**Issue by mikisingh** [FritzsHero/RoadArchitect#3]
I moved from the original to this fork due to the road flickering, which this took care of (THANKS!!).

It runs fine, but when I try to build I'm seeing these errors for PC: 

Assets\RoadArchitect\RoadConstructorBufferMaker.cs(197,21): error CS0246: The type or namespace name 'RoadUtility' could not be found (are you missing a using directive or an assembly reference?)

Assets\RoadArchitect\TerraformingThreaded.cs(703,24): error CS0246: The type or namespace name 'RoadUtility' could not be found (are you missing a using directive or an assembly reference?)

etc...

This from a simple new unity project in which i just create a terrain and slap some asphalt down, then build. Nothing more. When I switch back to the MicroGSD original, it compiles fine but I could run into road flickering if I expand the project.

Using Unity 2019.3.13.

Many thanks!
Miki

**Comment by FritzsHero** [comment]
Hello,

I fixed an build error which occurred in an empty project.
Can you apply the commit with the fix and confirm that your problem is also resolved?


Best Regards,

Fritzs

**Comment by mikisingh** [comment]
Awesome! Works great and thanks for keeping this going!
