### ISSUE TITLE
cant create road in unity

### ISSUE THREAD

**Issue by Pappy6617** [FritzsHero/RoadArchitect#33]
whenever i click shift or ctrl to create road in unity....it wont create any node only the terrain will show....please any help or solution to this....its really urgent

**Comment by FritzsHero** [comment]
Did you create a road system first?
Window -> Road Architect -> Create road system

**Comment by Okiski** [comment]
I had similar issue, after I changed editor layout to " default " it solved.

**Comment by FritzsHero** [comment]
No response. Closing this ticket.
