### ISSUE TITLE
pink textures

### ISSUE THREAD

**Issue by realR4PT0R1** [FritzsHero/RoadArchitect#34]
original textures are pink

**Comment by FritzsHero** [comment]
Are you using a SRP and not the built in render pipeline?
Because then you have to update all materials via the SRP wizard.

**Comment by handras** [comment]
I also encourted this when using in an URP project.
After updating the materilas with the wizard, the workflow mode has to be set to metallic, otherwise the roads are too glossy.

**Comment by FritzsHero** [comment]
No response. Closing this ticket.
