### ISSUE TITLE
How to make a car move along a close loop road

### ISSUE THREAD

**Issue by beurnii** [FritzsHero/RoadArchitect#40]
Hi,

I need to do a close loop road and make cars move in it. The cars are not player controlled and need to move at constant speed in there lanes forever in the loop.

Is this possible to do with road architect? I cannot find the functionality to do so. If not, do you know any other assets package that can?

**Comment by alippdeepsight** [comment]
bro get good

**Comment by FritzsHero** [comment]
This is not a functionality RoadArchitect currently provides.
