### ISSUE TITLE
Crash in Unity "Engine Patch - 2021.2.7f1"

### ISSUE THREAD

**Issue by Long981201** [FritzsHero/RoadArchitect#42]
**Description**
Hello I have a problem about Unity Crash when using road architect.

I open a terrain ( no edit, just  a plane ) and try to build road.
but it will crash like few while.

Is my unity engine too new for road architect ?
should i change engine to old version

And thank for who reply me, thank you so much.

**Comment by FritzsHero** [comment]
Hi,

that specific Unity version just might have some issues. I cannot reproduce this on 2021.2.11f1
Updating your Engine could help if you haven't already.

Best Regards

Fritzs
