### ISSUE TITLE
Not creating road

### ISSUE THREAD

**Issue by Gelli-VVN-Satyanarayana-Guptha** [FritzsHero/RoadArchitect#43]
Whenever I try to add a node on terrain by holding ctrl ,it doesn't create node instead it selects terrain.
I am using 2020 Lts version.
Plz help 🙏

**Comment by Makevelli** [comment]
Hello!
I had the same problem with another package (easyroads), before moving to Road Architect. What worked was changing the layout from the "Window" menu. After changing the layout you can edit it again to what it was configured before. Hope it works for you too.

**Comment by riccardone** [comment]
Toggle Visibility of all Gizmos in the scene view

**Comment by FritzsHero** [comment]
No response. Closing this ticket.
