### ISSUE TITLE
Add/Set first Node of a road by c#-script

### ISSUE THREAD

**Issue by 1026pa** [FritzsHero/RoadArchitect#49]
Hi,

I have multiple xyz coordanates and want to built a road based on them. In the script I already can add the road system but I cant set the first node. Can you say which command I need for this?
Its possible to do it pressing ctrl + mouse left, but I want to do it in the c# script so i can add multiple roads without clicking.

I would be very happy about an answer.
Thanks

**Comment by FritzsHero** [comment]
Hi,

have a look at the UnitTests script.


Best Regards

Fritzs

**Comment by FritzsHero** [comment]
No response. Closing this ticket.
