### ISSUE TITLE
Collisions at end of tunnel

### ISSUE THREAD

**Issue by siah01** [FritzsHero/RoadArchitect#6]
**Describe the bug**
When I add a tunnel to a Node using open wizard, my player vehicle seems to run into an invisible collider at the beginning or end of the tunnel. Deleting and re-creating the tunnel doesn't seem to help, but it does seem to change where collision is occurring. Moving nodes or adding nodes doesn't seem to help. Any advice?

**Expected behavior**
To drive through the tunnel and continue on road. 

**Unity version**
2019.2.0f1

**Additional context**

**Comment by embeddedt** [comment]
Is the tunnel going through terrain? It won't cut a hole in the terrain
collider.

**Comment by siah01** [comment]
No. See photo. 
![tunnel](https://user-images.githubusercontent.com/22032569/90339227-77cda400-dfbd-11ea-978a-e8fed679c0f5.JPG)
Here's video of what I'm seeing: https://photos.app.goo.gl/VfiGwiaovXgg5uHfA

**Comment by siah01** [comment]
Meh - pretty sure my issue has nothing to do w road architect. I deleted the entire road and had same issue on essentially a flat terrain. Closing issue.
